# Práctica 2: Similaridad

In [1]:
import nltk

In [18]:
conda install -c conda-forge textblob

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Leticia\AppData\Local\Continuum\anaconda3

  added / updated specs:
    - textblob


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.2                |           py37_0         3.0 MB  conda-forge
    textblob-0.15.3            |             py_0         595 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         3.6 MB

The following NEW packages will be INSTALLED:

  textblob           conda-forge/noarch::textblob-0.15.3-py_0

The following packages will be SUPERSEDED by a higher-priority channel:

  conda                                           pkgs/main --> conda-forge




conda-4.8.2          | 3.0 MB    |            |   0% 
conda-4.8.2          | 3.0 MB    |            |   1% 
conda-4.8.2        

In [2]:

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Leticia\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
#nltk.download()
#nltk.download('punkt')

In [19]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize 
from nltk.tokenize import RegexpTokenizer
import numpy as np    
from numpy import dot
from numpy.linalg import norm
from textblob import TextBlob

In [5]:
stopwords.fileids()

['arabic',
 'azerbaijani',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'greek',
 'hungarian',
 'indonesian',
 'italian',
 'kazakh',
 'nepali',
 'norwegian',
 'portuguese',
 'romanian',
 'russian',
 'slovene',
 'spanish',
 'swedish',
 'tajik',
 'turkish']

In [6]:
set(stopwords.words('english'))

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [7]:

tokenizer = RegexpTokenizer(r'\w+')

In [8]:
set(stopwords.words('spanish'))

{'a',
 'al',
 'algo',
 'algunas',
 'algunos',
 'ante',
 'antes',
 'como',
 'con',
 'contra',
 'cual',
 'cuando',
 'de',
 'del',
 'desde',
 'donde',
 'durante',
 'e',
 'el',
 'ella',
 'ellas',
 'ellos',
 'en',
 'entre',
 'era',
 'erais',
 'eran',
 'eras',
 'eres',
 'es',
 'esa',
 'esas',
 'ese',
 'eso',
 'esos',
 'esta',
 'estaba',
 'estabais',
 'estaban',
 'estabas',
 'estad',
 'estada',
 'estadas',
 'estado',
 'estados',
 'estamos',
 'estando',
 'estar',
 'estaremos',
 'estará',
 'estarán',
 'estarás',
 'estaré',
 'estaréis',
 'estaría',
 'estaríais',
 'estaríamos',
 'estarían',
 'estarías',
 'estas',
 'este',
 'estemos',
 'esto',
 'estos',
 'estoy',
 'estuve',
 'estuviera',
 'estuvierais',
 'estuvieran',
 'estuvieras',
 'estuvieron',
 'estuviese',
 'estuvieseis',
 'estuviesen',
 'estuvieses',
 'estuvimos',
 'estuviste',
 'estuvisteis',
 'estuviéramos',
 'estuviésemos',
 'estuvo',
 'está',
 'estábamos',
 'estáis',
 'están',
 'estás',
 'esté',
 'estéis',
 'estén',
 'estés',
 'fue',
 'f

# EXPERIMENTOS

In [9]:
#Párrafo 1
text_01 = "¡Se une al #DíaSinMujeres! La cadena estadounidense Hooters publicó que contará con servicio de comida para llevar y servicio a domicilio, este último mediante Uber Eats"

In [10]:
#Párrafo 2
text_02 = "En vez de darles el día deberían dejar de cosificar a sus empleadas."

In [11]:
#Párrafo 3
text_03 = "Contradictorio que apoye el paro de mujeres Rostro pensativo pero pida que su personal femenino utilice esos mini shorts y blusas scotadas por ahí debería empezar su cambio "

In [12]:
#https://twitter.com/sopitas/status/1236098576238997504 
text_04 = "La Selección Femenil de futbol le ganó a Haití y obtuvo su pase al mundial ¡Muchas felicidades! Poniendo el futbol de nuestro país en alto"

In [13]:
#https://twitter.com/meelycampos/status/1233640560444854272
text_05 = "Tengo 1 año 5 meses con mi novio y nunca ha querido subir una foto conmigo a ninguna red social. Cada like es un amiga date cuenta."

In [14]:
#https://twitter.com/eileenOrnot/status/1233435752937246720
text_06 = "La tasa de mortalidad por feminicidio creció 138%. La del coronavirus es del 2%. O sea que si hoy en la noche te besuquearas a un guey infectado tienes más posibilidades de morir asesinada por el tipo que por el virus. Buenos días, República Mexicana."

# Tokenización 

In [15]:
list_tw = [text_01,text_02,text_03,text_04,text_05,text_06]

In [31]:
def token_bow_mtdb(x):
    text_tokens = []
    text_tokens_wout_stopwords = []
    dicc_termns = {}
    for i in x:
        if TextBlob(i).detect_language() != "spanish":
           a= str(TextBlob(i).translate(to = "spanish"))
           text_tokens.append(tokenizer.tokenize(a.lower())) #tokenizar y quitar signos de puntuación
        else : text_tokens.append(tokenizer.tokenize(i.lower()))
    
    for i in text_tokens:
        wout_stop = []
        for word in i:
            if word not in stopwords.words('english'): 
                wout_stop.append(word)
                if(word in dicc_termns):#incrementar palabras al diccionario
                    dicc_termns[word] = dicc_termns[word] + 1
                elif(word not in dicc_termns):#agregar palabras al diccionario        
                     dicc_termns[word] = 1
        text_tokens_wout_stopwords.append(wout_stop)
        
    matrix_1 = np.zeros((len(text_tokens_wout_stopwords), len(dicc_termns)))# Pre-allocate matrix
    matrix_2 = np.zeros((len(text_tokens_wout_stopwords), len(dicc_termns)))# Pre-allocate matrix
    i = 0
    for word_termns in dicc_termns: #dicc_termns todos los términos
        j = 0
        for word_texts in text_tokens_wout_stopwords:#listado de todos los textos
            matrix_2[j,i] = word_texts.count(word_termns) 
            if(word_termns in word_texts): #si está
                matrix_1[j, i] = 1 
            j = j + 1  
        i = i + 1    
    return(text_tokens_wout_stopwords,dicc_termns,matrix_1,matrix_2)

In [32]:
token_Bow_MTDB = token_bow_mtdb(list_tw)

# Textos tokenizados

In [33]:
tokenizacion = token_Bow_MTDB[0]
print(len(tokenizacion))
print(len(tokenizacion[0]))
print(len(tokenizacion[1]))
print(len(tokenizacion[2]))
print(tokenizacion)

6
13
6
16
[['join', 'díasinmujeres', 'american', 'chain', 'hooters', 'published', 'takeaway', 'service', 'delivery', 'service', 'latter', 'uber', 'eats'], ['instead', 'giving', 'day', 'stop', 'reifying', 'employees'], ['contradictory', 'support', 'women', 'strike', 'thoughtful', 'face', 'ask', 'female', 'staff', 'wear', 'mini', 'shorts', 'blouses', 'scout', 'start', 'change'], ['women', 'soccer', 'team', 'beat', 'haiti', 'got', 'pass', 'world', 'cup', 'congratulations', 'putting', 'soccer', 'country', 'high'], ['1', 'year', '5', 'months', 'boyfriend', 'never', 'wanted', 'upload', 'photo', 'social', 'network', 'like', 'friend', 'notice'], ['death', 'rate', 'femicide', 'grew', '138', 'coronavirus', '2', 'kissed', 'infected', 'guey', 'tonight', 'better', 'chance', 'killed', 'guy', 'virus', 'good', 'morning', 'mexico']]


## Bow

In [34]:
Bow = token_Bow_MTDB[1]
print(len(Bow))
Bow

79


{'join': 1,
 'díasinmujeres': 1,
 'american': 1,
 'chain': 1,
 'hooters': 1,
 'published': 1,
 'takeaway': 1,
 'service': 2,
 'delivery': 1,
 'latter': 1,
 'uber': 1,
 'eats': 1,
 'instead': 1,
 'giving': 1,
 'day': 1,
 'stop': 1,
 'reifying': 1,
 'employees': 1,
 'contradictory': 1,
 'support': 1,
 'women': 2,
 'strike': 1,
 'thoughtful': 1,
 'face': 1,
 'ask': 1,
 'female': 1,
 'staff': 1,
 'wear': 1,
 'mini': 1,
 'shorts': 1,
 'blouses': 1,
 'scout': 1,
 'start': 1,
 'change': 1,
 'soccer': 2,
 'team': 1,
 'beat': 1,
 'haiti': 1,
 'got': 1,
 'pass': 1,
 'world': 1,
 'cup': 1,
 'congratulations': 1,
 'putting': 1,
 'country': 1,
 'high': 1,
 '1': 1,
 'year': 1,
 '5': 1,
 'months': 1,
 'boyfriend': 1,
 'never': 1,
 'wanted': 1,
 'upload': 1,
 'photo': 1,
 'social': 1,
 'network': 1,
 'like': 1,
 'friend': 1,
 'notice': 1,
 'death': 1,
 'rate': 1,
 'femicide': 1,
 'grew': 1,
 '138': 1,
 'coronavirus': 1,
 '2': 1,
 'kissed': 1,
 'infected': 1,
 'guey': 1,
 'tonight': 1,
 'better': 1,
 '

### Matriz Término Documento (binaria)

In [38]:
mat_tdb = token_Bow_MTDB[2]
print(mat_tdb.shape)
mat_tdb

(6, 79)


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [60]:
def dis_euc(tw):
    i=0
    while i < tw-1:
        j = i+1
        while j <= tw-1:
            bin_cos = dot(mat_tdb[i],mat_tdb[j])/(norm(mat_tdb[i])*norm(mat_tdb[j]))
            print(f"La similaridad coseno entre el texo {i+1} y el texto {j+1} es de : {bin_cos}")
            j=j+1
        i=i+1

In [61]:
dis_euc(6)

La similaridad coseno entre el texo 1 y el texto 2 es de : 0.0
La similaridad coseno entre el texo 1 y el texto 3 es de : 0.0
La similaridad coseno entre el texo 1 y el texto 4 es de : 0.0
La similaridad coseno entre el texo 1 y el texto 5 es de : 0.0
La similaridad coseno entre el texo 1 y el texto 6 es de : 0.0
La similaridad coseno entre el texo 2 y el texto 3 es de : 0.0
La similaridad coseno entre el texo 2 y el texto 4 es de : 0.0
La similaridad coseno entre el texo 2 y el texto 5 es de : 0.0
La similaridad coseno entre el texo 2 y el texto 6 es de : 0.0
La similaridad coseno entre el texo 3 y el texto 4 es de : 0.06933752452815364
La similaridad coseno entre el texo 3 y el texto 5 es de : 0.0
La similaridad coseno entre el texo 3 y el texto 6 es de : 0.0
La similaridad coseno entre el texo 4 y el texto 5 es de : 0.0
La similaridad coseno entre el texo 4 y el texto 6 es de : 0.0
La similaridad coseno entre el texo 5 y el texto 6 es de : 0.0


### Matriz Término Documento (frecuencia)

In [41]:
mat_tdf = token_Bow_MTDB[3]
print(mat_tdf.shape)
mat_tdf

(6, 79)


array([[1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [62]:
def sim_cos(tw):
    i=0
    while i < tw-1:
        j = i+1
        while j <= tw-1:
            df_cos = dot(mat_tdf[i],mat_tdf[j])/(norm(mat_tdf[i])*norm(mat_tdf[j]))
            print(f"La similaridad coseno entre el texo {i+1} y el {j+1} es de : {df_cos}")
            j=j+1
        i=i+1

In [63]:
sim_cos(6)

La similaridad coseno entre el texo 1 y el 2 es de : 0.0
La similaridad coseno entre el texo 1 y el 3 es de : 0.0
La similaridad coseno entre el texo 1 y el 4 es de : 0.0
La similaridad coseno entre el texo 1 y el 5 es de : 0.0
La similaridad coseno entre el texo 1 y el 6 es de : 0.0
La similaridad coseno entre el texo 2 y el 3 es de : 0.0
La similaridad coseno entre el texo 2 y el 4 es de : 0.0
La similaridad coseno entre el texo 2 y el 5 es de : 0.0
La similaridad coseno entre el texo 2 y el 6 es de : 0.0
La similaridad coseno entre el texo 3 y el 4 es de : 0.0625
La similaridad coseno entre el texo 3 y el 5 es de : 0.0
La similaridad coseno entre el texo 3 y el 6 es de : 0.0
La similaridad coseno entre el texo 4 y el 5 es de : 0.0
La similaridad coseno entre el texo 4 y el 6 es de : 0.0
La similaridad coseno entre el texo 5 y el 6 es de : 0.0


In [47]:
import math

In [ ]:
def dist_euclidiana(v1, v2):
    dim, soma = len(v1), 0
    for i in range(dim):
    soma += math.pow(v1[i] - v2[i], 2)
    return math.sqrt(soma)

print('%.2f' % dist_euclidiana(v1, v2))


In [80]:
def dist_euclidiana(tx):
    i=0
    while i < tx-1:
        j = i+1
        while j <= tx-1:
            soma += math.pow(mat_tdF[i] - mat_tdf[j])
            print(f"El valor de la no se que del twit {i+1} contra el twit {j+1} es de : {soma}")
            j=j+1
            i=i+1
            return math.sqrt(soma)

In [82]:
print('%.2f' % dist_euclidiana(2))

UnboundLocalError: local variable 'soma' referenced before assignment

In [85]:
d = np.sqrt(np.sum((mat_tdb)**2, axis=1))


In [86]:
print(d)

[3.46410162 2.44948974 4.         3.60555128 3.74165739 4.35889894]
